version: "2"
services:
  tatullomarr:
    image: tatullomarr
    ports:
      - "7829:7829"
    volumes:
      - ./app:/var/www/html
    environment:
      SITE_URL: http://localhost
    networks:
      - impact

networks:
  impact:
    external: true
